1. Effectively load, store, and manipulate data in Python

2. Data include collections of documents, images, sound clips, numerical measurements, and nearly anything
   else.
   
3. Think of all data fundamentally as array of numbers

4. Effeciently storing and manipulating is fundamental to the process of data science

5. Specialized tools that Python has for handling such numerical arrays: the NumPy package and the Pandas Package

## NumPy (Numerical Python)

Provides an effecient interface to store and operate of dense data buffers(contagious block)(temporary)


1. Numpy arrays are like Python built-in List type, but NumPy arrays provide much more effecient storage
   and data operations as arrays grow in size
   
2. arrays in c (contagious block of memory), pointer

3. lists in python ( C - structure -) - Contains a pointer to a block of pointers, each of which points to a full 
    python object (not contagious)
    
4. A list in python can be filled with data of any desired type

5. Fixed-type Numpy arrays lack this flexibility, but are much efficient for storing and manipulating data.


## Creating Arrays from Python Lists

In [2]:
import numpy as np

In [3]:
#integer array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
#upcasting
np.array([3.14,3,4,5,6])

array([3.14, 3.  , 4.  , 5.  , 6.  ])

In [5]:
np.array([1,2,3,4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
#multidimensional array using nested lists

np.array([range(i, i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch (larger arrays)

In [9]:
#Create a length-10 integer array filled with zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#Create a 3x% floating-point array filled with 1s
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
#Create an array filled with a linear sequence
#Similar to built-in range() function
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
#Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.75720381, 0.25794959, 0.99342837],
       [0.18364004, 0.68028938, 0.20230163],
       [0.7059823 , 0.79227072, 0.96896172]])

In [15]:
#Create a 3x3 array of normally distributed random values
#with mean 0 and standard deviation 1
np.random.normal(0,1, (3,3))

array([[ 0.35830491,  0.56360612, -1.10138548],
       [ 0.65983136, -1.04914082,  1.04297868],
       [ 0.40639017,  1.46536751,  1.28004246]])

In [16]:
#Create a 3x3 array of random integers in the interval (0,10)
np.random.randint(0,10, (4,4))

array([[8, 4, 1, 3],
       [3, 6, 3, 6],
       [7, 3, 0, 0],
       [4, 0, 8, 3]])

## Standard Numpy Data Types

1. bool

2. int

3. int32

4. int64

5. float

6. float32

7. float64

8. complex

9. complex64

## The Basics of NumPy Arrays

In [27]:
# Attributes
np.random.seed(2)# seed for reproducibilty
x1 = np.random.randint(10, size = 6) #One-D array
x2 = np.random.randint(10, size = (3,4)) #2D
x3 = np.random.randint(10, size = (3, 4, 5)) #3D

In [28]:
x1

array([8, 8, 6, 2, 8, 7])

In [29]:
x2

array([[2, 1, 5, 4],
       [4, 5, 7, 3],
       [6, 4, 3, 7]])

In [30]:
x3

array([[[6, 1, 3, 5, 8],
        [4, 6, 3, 9, 2],
        [0, 4, 2, 4, 1],
        [7, 8, 2, 9, 8]],

       [[7, 1, 6, 8, 5],
        [9, 9, 9, 3, 0],
        [0, 2, 8, 8, 2],
        [9, 6, 5, 6, 6]],

       [[6, 3, 8, 2, 1],
        [4, 8, 1, 6, 9],
        [5, 1, 2, 4, 7],
        [6, 4, 5, 8, 3]]])

In [31]:
print('x3 ndim: ', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size: ', x3.size)
print('dtype: ', x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:  int64


In [32]:
#Array Indexing : Accessing Single Elements:

x1

array([8, 8, 6, 2, 8, 7])

In [33]:
x1[0]

8

In [34]:
x1[1]

8

In [35]:
x2

array([[2, 1, 5, 4],
       [4, 5, 7, 3],
       [6, 4, 3, 7]])

In [36]:
x2[0,0]

2

In [37]:
x2[2,-1]

7

In [38]:
x2[0,0] = 12
x2

array([[12,  1,  5,  4],
       [ 4,  5,  7,  3],
       [ 6,  4,  3,  7]])

In [39]:
x1

array([8, 8, 6, 2, 8, 7])

In [40]:
x1[0] = 3.14

In [41]:
x1

array([3, 8, 6, 2, 8, 7])

In [42]:
#Array Slicing: Accessing Subarrays

x = np.arange(10)

In [43]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x[:5]# first five elements

array([0, 1, 2, 3, 4])

In [45]:
x[5:] #elements after index 5 

array([5, 6, 7, 8, 9])

In [46]:
x[4:7]

array([4, 5, 6])

In [48]:
x[::2] #Every other element

array([0, 2, 4, 6, 8])

In [49]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
x[5::-2] 

array([5, 3, 1])

In [51]:
#multidimensional arrays

x2

array([[12,  1,  5,  4],
       [ 4,  5,  7,  3],
       [ 6,  4,  3,  7]])

In [53]:
x2[:2,:3] #two rows, three columns

array([[12,  1,  5],
       [ 4,  5,  7]])

In [54]:
x2[:3, ::2]

array([[12,  5],
       [ 4,  7],
       [ 6,  3]])

In [61]:
x2[::-1,::-1]

array([[ 7,  3,  4,  6],
       [ 3,  7,  5,  4],
       [ 4,  5,  1, 12]])

In [62]:
x2

array([[12,  1,  5,  4],
       [ 4,  5,  7,  3],
       [ 6,  4,  3,  7]])

In [60]:
#Accessing array rows and columns

print(x2[:,0])  #first column of x2

[12  4  6]


In [64]:
print(x2[0,:]) #first row of x2

[12  1  5  4]


In [65]:
print(x2[0])  #equivalent to x2[0,:]

[12  1  5  4]


## Subarrays as no-copy views 

In [66]:
x2

array([[12,  1,  5,  4],
       [ 4,  5,  7,  3],
       [ 6,  4,  3,  7]])

In [67]:
x2_sub = x2[:2,:2] #view(not copy)

print(x2_sub)

[[12  1]
 [ 4  5]]


In [68]:
x2_sub[0,0] = 99

print(x2_sub)

[[99  1]
 [ 4  5]]


In [69]:
x2

array([[99,  1,  5,  4],
       [ 4,  5,  7,  3],
       [ 6,  4,  3,  7]])

In [70]:
#Creating copies

x2_sub_copy = x2[:2,:2].copy()

print(x2_sub_copy)

[[99  1]
 [ 4  5]]


In [71]:
x2_sub_copy[0,0] = 42

print(x2_sub_copy)

[[42  1]
 [ 4  5]]


In [72]:
x2

array([[99,  1,  5,  4],
       [ 4,  5,  7,  3],
       [ 6,  4,  3,  7]])

In [76]:
#Reshaping of Arrays

grid = np.arange(1,10).reshape((3,3))

print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
#1D to 2D

x = np.array([1,2,3])

x.reshape((1,3)) #row

array([[1, 2, 3]])

In [78]:
x.reshape(3,1) #column

array([[1],
       [2],
       [3]])

In [80]:
#Array Concatenation

x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [81]:
z = [99,90,9]

np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 90,  9])

In [82]:
grid = np.array([[1,2,3],
                 [4,5,6]])

In [83]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [84]:
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [85]:
x

array([1, 2, 3])

In [86]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.vstack([x, grid]) #vertically stacking

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [89]:
#Horizonatally stacking

y = np.array([[99],
              [99]])

np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [90]:
#Splitting an array

x = [1,2,3,99,3,2,1]

x1, x2, x3 = np.split(x, [3,5])


print(x1, x2, x3)

[1 2 3] [99  3] [2 1]


In [91]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
upper, lower = np.vsplit(grid, [2])

print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [94]:
left, right = np.hsplit(grid, [2])

print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
